### ISSUE TITLE
ESPHome Compiler fails "no attribute 'validate_pillow_installed'"

### ISSUE THREAD

**Issue by BbMaj7** [lubeda/EspHoMaTriXv2#262]
# Question

I have tried EspHoMaTriX and EspHoMaTriXv2 for some time - both fail with the same error. It is probably not an issue but I am out of ideas. I have simplified the YAML. Can anyone point me into a direction?

## Additional information

- used Hardware:
  - ESP8266 as D1 mini (by AZ-Delivery, confirmed working)

- used Software:
  - EspHoMaTriXv2 version: [latest: 2024.12.1]
  - ESPHome-Version [2024.12.0-dev]
  - Home Assistant 2024.12.1 on Rasperry Pi 4

## Logs

```text
INFO ESPHome 2024.12.0-dev
INFO Reading configuration /config/esphome/esphome-web-f0f516.yaml...
WARNING Found '$devicename Light' (see light->0->name) which looks like a substitution, but 'devicename' was not declared
WARNING Found '$devicename Light' (see light->0->name) which looks like a substitution, but 'devicename' was not declared
WARNING 
WARNING This will only work with esphome >= 2023.7.0
WARNING Please check the documentation and wiki https://github.com/lubeda/EspHoMaTriXv2
WARNING 
ERROR Unable to load component ehmtxv2:
Traceback (most recent call last):
  File "/esphome/esphome/loader.py", line 177, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/esphome/components/ehmtxv2/__init__.py", line 247, in <module>
    CONFIG_SCHEMA = cv.All(font.validate_pillow_installed, EHMTX_SCHEMA)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'esphome.components.font' has no attribute 'validate_pillow_installed'
Failed config

ehmtxv2: [source /config/esphome/esphome-web-f0f516.yaml:114]
  
  Component not found: ehmtxv2.
  id: rgb8x32
  icons2html: True
```

**Comment by lubeda** [comment]
See here https://github.com/lubeda/EspHoMaTriXv2/issues/261
